version: '3'


volumes:
  reef:


services:
  reef:
    build: .
    image: "t2b/reefcon"
    ports:
     - "800-810:800-810"
    volumes:
     - "reef:/rdat"
    environment:
     - Reef_Key=Reef
     - Reef_Path='/rdat'
    command: "/reef/API_Daemon.sh -up; tail -F anything"
